apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -canary
labels:
  - pairs:
      app.kubernetes.io/instance: canary
    includeSelectors: true
    includeTemplates: true
patches:
  - target:
      kind: ConfigMap
      name: ores-gh-bots-config
    patch: |-
      - op: add
        path: /data/LOG_LEVEL
        value: debug
      - op: replace
        path: /data/RECONCILE_INTERVAL_MS
        value: "300000"
