apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - pairs:
      app.kubernetes.io/instance: production
    includeSelectors: true
    includeTemplates: true
images:
  - name: ghcr.io/oresoftware/ores-gh-bots
    newTag: v0.1.0
